cod1 = int(input())
numer_peca1 = int(input())
valor_peca1 = float(input())
cod2 = int(input())
numer_peca2 = int(input())
valor_peca2 = float(input())
calculo = (numer_peca1 * valor_peca1) + (numer_peca2 * valor_peca2)
print('VALOR A PAGAR = R$ {}'.format(calculo))
